"""empty message

Revision ID: 84621a173b16
Revises: 
Create Date: 2019-07-02 09:41:24.992333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84621a173b16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pileups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('pileup_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('reference_base', sa.String(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('read_results', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pileup_id'], ['pileups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seqruns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('sequencing_type', sa.String(), nullable=True),
    sa.Column('machine', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fastqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('seqrun_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('instrument_id', sa.String(), nullable=True),
    sa.Column('flow_cell_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('type_instrument', sa.String(), nullable=True),
    sa.Column('type_sequencing', sa.String(), nullable=True),
    sa.Column('docs', sa.String(), nullable=True),
    sa.Column('sequence', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('read_quality', sa.String(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('tile_number', sa.Integer(), nullable=True),
    sa.Column('x_coord', sa.Integer(), nullable=True),
    sa.Column('y_coord', sa.Integer(), nullable=True),
    sa.Column('member_pair', sa.Integer(), nullable=True),
    sa.Column('read_filter', sa.String(), nullable=True),
    sa.Column('control_bits', sa.Integer(), nullable=True),
    sa.Column('index_for', sa.String(), nullable=True),
    sa.Column('index_rev', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['seqrun_id'], ['seqruns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pileupfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('full_search_sequence', sa.String(), nullable=True),
    sa.Column('target_sequence', sa.String(), nullable=True),
    sa.Column('index_for', sa.String(), nullable=True),
    sa.Column('index_rev', sa.String(), nullable=True),
    sa.Column('sample_uuid', sa.String(), nullable=True),
    sa.Column('seqrun_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seqrun_id'], ['seqruns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('seqrun_id', sa.Integer(), nullable=False),
    sa.Column('bigseq', sa.String(), nullable=True),
    sa.Column('alignment_tool', sa.String(), nullable=True),
    sa.Column('alignment_tool_version', sa.String(), nullable=True),
    sa.Column('index_for', sa.String(), nullable=True),
    sa.Column('index_rev', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['seqrun_id'], ['seqruns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('samfile_id', sa.Integer(), nullable=False),
    sa.Column('qname', sa.String(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('rname', sa.String(), nullable=True),
    sa.Column('pos', sa.Integer(), nullable=True),
    sa.Column('mapq', sa.Integer(), nullable=True),
    sa.Column('cigar', sa.String(), nullable=True),
    sa.Column('rnext', sa.String(), nullable=True),
    sa.Column('pnext', sa.Integer(), nullable=True),
    sa.Column('tlen', sa.Integer(), nullable=True),
    sa.Column('seq', sa.String(), nullable=True),
    sa.Column('qual', sa.String(), nullable=True),
    sa.Column('tp', sa.String(), nullable=True),
    sa.Column('cm', sa.String(), nullable=True),
    sa.Column('s1', sa.String(), nullable=True),
    sa.Column('s2', sa.String(), nullable=True),
    sa.Column('NM', sa.String(), nullable=True),
    sa.Column('MD', sa.String(), nullable=True),
    sa.Column('AS', sa.String(), nullable=True),
    sa.Column('ms', sa.String(), nullable=True),
    sa.Column('nn', sa.String(), nullable=True),
    sa.Column('ts', sa.String(), nullable=True),
    sa.Column('cg', sa.String(), nullable=True),
    sa.Column('cs', sa.String(), nullable=True),
    sa.Column('dv', sa.String(), nullable=True),
    sa.Column('de', sa.String(), nullable=True),
    sa.Column('rl', sa.String(), nullable=True),
    sa.Column('SA', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['samfile_id'], ['samfiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sams')
    op.drop_table('samfiles')
    op.drop_table('pileupfiles')
    op.drop_table('fastqs')
    op.drop_table('seqruns')
    op.drop_table('pileups')
    op.drop_table('jobs')
    # ### end Alembic commands ###
