"""empty message

Revision ID: d94b1b9767b9
Revises: 84621a173b16
Create Date: 2019-07-02 09:52:15.062709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94b1b9767b9'
down_revision = '84621a173b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seqruns', sa.Column('well', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seqruns', 'well')
    # ### end Alembic commands ###
